name: Atualizar Índice de Markdown

on:
  push:
    branches:
      - main

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Inicializar o JSON
        run: echo "[" > md.json

      - name: Encontrar todos os arquivos .md no repositório
        run: |
          find . -name "*.md" ! -path "./md.json" ! -path "./README.md" | while read file; do
            filename=$(basename "$file")
            filepath=$(realpath --relative-to=. "$file")
            name=$(basename "$file" .md)
            echo "  { \"name\": \"${name}\", \"filename\": \"${filename}\", \"path\": \"${filepath}\" }," >> md.json
          done
          sed -i '$ s/,$//' md.json
          echo "]" >> md.json

      - name: Configurar Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Commit and push changes
        run: |
          git add md.json
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
          else
            git commit -m "Atualiza índice de arquivos Markdown em JSON"
            git push
          fi
